org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# Maven Publishing
GROUP=io.github.ajitkumarmaurya
VERSION_NAME=1.0.1
POM_NAME=imdb-kt
POM_DESCRIPTION=A production-ready Kotlin library for crawling and parsing IMDb metadata
POM_URL=https://github.com/AjitkumarMaurya/imdbkt
POM_LICENSE_NAME=Apache-2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_DEVELOPER_ID=AjitkumarMaurya
POM_DEVELOPER_NAME=Ajit Kumar Maurya
POM_DEVELOPER_EMAIL=your@email.com
POM_SCM_URL=https://github.com/AjitkumarMaurya/imdbkt
POM_SCM_CONNECTION=scm:git:git://github.com/AjitkumarMaurya/imdbkt.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/AjitkumarMaurya/imdbkt.git
android.builtInKotlin=false
android.newDsl=false
